# Generated by Django 3.2.9 on 2021-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя актера')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сценариста')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('imdb', models.BooleanField(default=0.0, verbose_name='Рейтинг фильма')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанры')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('writers_names', models.TextField(verbose_name='Список имен сценаристов, разделенных запятыми')),
                ('director', models.CharField(max_length=255, verbose_name='Режисер')),
                ('actors_names', models.TextField(verbose_name='Список имен актеров, разделенных запятыми')),
                ('actors', models.ManyToManyField(to='main.Actor', verbose_name='Актеры')),
                ('writers', models.ManyToManyField(related_name='Режисеры', to='main.Writer')),
            ],
        ),
    ]
