# Generated by Django 3.2.9 on 2021-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг фильма'),
        ),
    ]
